title: GM Izi bizi
description: >
  Die Guggenmusig Izi bizi tini wini macht seit 1986 die Fasnacht in Herisau
  und Umgebung unsicher. Die Freude an der Musik und der Gemeinschaftsgedanke
  stehen dabei im Vordergrund.
author: Manuel Hutter (https://hutter.io)
logo: /img/izi-logo.png
baseurl: ''
url: https://www.izibizi.ch

nav:
  GM Izi bizi tini wini: /
  Termine: /#termine
  Mitglieder: /mitglieder/
  Bilder: /bilder/
  Schnitzelbänke: /schnitzelbank/2015/
  Links: /links/
  VHG: /vhg/

permalink: pretty

collections:
  schnitzelbank:
    output: true
  mitglieder:
    output: true

# Defaults
defaults:
  - scope:
      path: "" # anything
    values:
      layout: default
  - scope:
      path: "" # anything
      type: schnitzelbank
    values:
      layout: schnitzelbank
  - scope:
      path: ""
      type: mitglieder
    values:
      layout: mitglied

# Build settings
markdown: kramdown
sass:
  style: compressed

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Rakefile
  - Gemfile.lock
